-- MySQL Script generated by MySQL Workbench
-- 12/03/14 21:01:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cbscalendar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cbscalendar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cbscalendar` DEFAULT CHARACTER SET utf8 ;
USE `cbscalendar` ;

-- -----------------------------------------------------
-- Table `cbscalendar`.`calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbscalendar`.`calendar` (
  `calendarid` INT(11) NOT NULL AUTO_INCREMENT,
  `calendarname` VARCHAR(255) NOT NULL,
  `createdby` VARCHAR(255) NOT NULL,
  `privatepublic` TINYINT(4) NOT NULL COMMENT '1 = public\n	2 = private',
  `active` TINYINT(4) NOT NULL,
  PRIMARY KEY (`calendarid`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cbscalendar`.`dailyupdate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbscalendar`.`dailyupdate` (
  `date` DATETIME NOT NULL,
  `apparenttemperature` DOUBLE NULL DEFAULT NULL,
  `summary` TEXT NULL DEFAULT NULL,
  `qotd` VARCHAR(300) NOT NULL,
  `msg_type` VARCHAR(100) NOT NULL,
  `update_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`date`),
  UNIQUE INDEX `date` (`date` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cbscalendar`.`locationdata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbscalendar`.`locationdata` (
  `locationdataid` INT(11) NOT NULL AUTO_INCREMENT,
  `longitude` INT(11) NOT NULL,
  `latitude` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`locationdataid`),
  UNIQUE INDEX `latitude` (`latitude` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cbscalendar`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbscalendar`.`users` (
  `userid` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(40) NOT NULL,
  `active` TINYINT(5) NOT NULL,
  `created` DATETIME NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cbscalendar`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbscalendar`.`events` (
  `eventid` INT(11) NOT NULL AUTO_INCREMENT,
  `location` INT(11) NULL DEFAULT NULL,
  `createdby` INT(11) NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `eventname` VARCHAR(100) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  `calendarid` INT(11) NOT NULL,
  `active` TINYINT(4) NOT NULL,
  `customevent` TINYINT(1) NULL DEFAULT NULL COMMENT 'Decides wether the event is an import-event or user created\n',
  PRIMARY KEY (`eventid`),
  INDEX `calendarid` (`calendarid` ASC),
  INDEX `location` (`location` ASC),
  INDEX `createdby` (`createdby` ASC),
  CONSTRAINT `events_ibfk_1`
    FOREIGN KEY (`calendarid`)
    REFERENCES `cbscalendar`.`calendar` (`calendarid`),
  CONSTRAINT `events_ibfk_2`
    FOREIGN KEY (`location`)
    REFERENCES `cbscalendar`.`locationdata` (`locationdataid`),
  CONSTRAINT `events_ibfk_3`
    FOREIGN KEY (`createdby`)
    REFERENCES `cbscalendar`.`users` (`userid`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cbscalendar`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbscalendar`.`notes` (
  `noteid` INT(11) NOT NULL AUTO_INCREMENT,
  `eventid` INT(11) NOT NULL,
  `createdby` VARCHAR(255) NOT NULL,
  `note` VARCHAR(2000) NULL DEFAULT NULL,
  `dateTime` DATETIME NOT NULL,
  `active` TINYINT(4) NOT NULL,
  PRIMARY KEY (`noteid`),
  INDEX `eventid` (`eventid` ASC),
  CONSTRAINT `notes_ibfk_1`
    FOREIGN KEY (`eventid`)
    REFERENCES `cbscalendar`.`events` (`eventid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cbscalendar`.`userevents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbscalendar`.`userevents` (
  `userid` INT(11) NOT NULL,
  `calendarid` INT(11) NOT NULL,
  INDEX `calendarid` (`calendarid` ASC),
  INDEX `userid` (`userid` ASC),
  CONSTRAINT `userevents_ibfk_1`
    FOREIGN KEY (`calendarid`)
    REFERENCES `cbscalendar`.`calendar` (`calendarid`),
  CONSTRAINT `userevents_ibfk_2`
    FOREIGN KEY (`userid`)
    REFERENCES `cbscalendar`.`users` (`userid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
